{
 "title": "Physical RU Power Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RU 1 - Instant Energy Usage (Watt/Hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shelly1_energy_wh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RU 2 - Instant Energy Usage (Watt/Hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shelly2_energy_wh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RU 2 - Instant Power consumption/Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "shelly2_power_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RU 1 - Instant Power consumption/Watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "shelly1_power_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RUs Instant Current Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "shelly1_current_a", "legendFormat": "__auto" },
    { "expr": "shelly2_current_a", "legendFormat": "__auto" }
   ]
  }
 ]
}